version: '3'

services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: i@d_root_pass
       MYSQL_DATABASE: i@d_test
       MYSQL_USER: i@d_user
       MYSQL_PASSWORD: i@d_pass

   php:
     build: .
     depends_on:
       - db
     volumes:
       - ./project:/usr/src/project/
     ports:
       - "8000:8000"
     restart: always

volumes:
    db_data:
